import { expect, test } from "bun:test"

import { Setup, SxClass } from "lib/sexpr"

test("Setup", () => {
  const [setup] = SxClass.parse(`
(setup
  (stackup
    (layer "F.SilkS"
      (type "Top Silk Screen")
    )
    (layer "dielectric 1"
      (type "core")
      (thickness 1.51)
      (material "FR4")
      (epsilon_r 4.5)
      (loss_tangent 0.02)
    )
    (copper_finish "None")
    (dielectric_constraints no)
  )
  (pad_to_mask_clearance 0)
  (solder_mask_min_width 0.01)
  (pad_to_paste_clearance 0)
  (pad_to_paste_clearance_ratio 0)
  (last_trace_width 0.254)
  (trace_clearance 0.254)
  (zone_clearance 0.2)
  (zone_45_only no)
  (trace_min 0.254)
  (segment_width 0.2)
  (edge_width 0.15)
  (via_size 0.889)
  (via_drill 0.635)
  (via_min_size 0.889)
  (via_min_drill 0.508)
  (uvia_size 0.508)
  (uvia_drill 0.127)
  (uvias_allowed no)
  (uvia_min_size 0.508)
  (uvia_min_drill 0.127)
  (pcb_text_width 0.3)
  (pcb_text_size 1.5 1.5)
  (mod_edge_width 0.15)
  (mod_text_size 1.5 1.5)
  (mod_text_width 0.15)
  (pad_size 0.0005 0.0005)
  (pad_drill 0)
  (allow_soldermask_bridges_in_footprints no)
  (tenting front back)
  (aux_axis_origin 10 15)
  (grid_origin 20 25)
  (visible_elements 7FFFFFFF)
  (pcbplotparams
    (layerselection 0x00000000_00000000_00000000_000000a5)
    (plot_on_all_layers_selection 0x00000000_00000000_00000000_00000000)
    (disableapertmacros no)
    (usegerberextensions yes)
    (usegerberattributes no)
    (usegerberadvancedattributes no)
    (creategerberjobfile no)
    (dashed_line_dash_ratio 12)
    (dashed_line_gap_ratio 3)
    (svgprecision 6)
    (plotframeref no)
    (mode 1)
    (useauxorigin no)
    (hpglpennumber 1)
    (hpglpenspeed 20)
    (hpglpendiameter 15)
    (pdf_front_fp_property_popups yes)
    (pdf_back_fp_property_popups yes)
    (pdf_metadata yes)
    (pdf_single_document no)
    (dxfpolygonmode yes)
    (dxfimperialunits yes)
    (dxfusepcbnewfont yes)
    (psnegative no)
    (psa4output no)
    (plot_black_and_white yes)
    (plotinvisibletext no)
    (sketchpadsonfab no)
    (plotpadnumbers no)
    (hidednponfab no)
    (sketchdnponfab yes)
    (crossoutdnponfab yes)
    (subtractmaskfromsilk no)
    (outputformat 1)
    (mirror no)
    (drillshape 1)
    (scaleselection 1)
    (outputdirectory "")
  )
)
`)

  expect(setup).toBeInstanceOf(Setup)
  expect(setup!.getString()).toMatchInlineSnapshot(`
    "(setup
      (stackup
        (layer \"F.SilkS\"
          (type \"Top Silk Screen\")
        )
        (layer \"dielectric 1\"
          (type \"core\")
          (thickness 1.51)
          (material \"FR4\")
          (epsilon_r 4.5)
          (loss_tangent 0.02)
        )
        (copper_finish \"None\")
        (dielectric_constraints no)
      )
      (pad_to_mask_clearance 0)
      (solder_mask_min_width 0.01)
      (pad_to_paste_clearance 0)
      (pad_to_paste_clearance_ratio 0)
      (last_trace_width 0.254)
      (trace_clearance 0.254)
      (zone_clearance 0.2)
      (zone_45_only no)
      (trace_min 0.254)
      (segment_width 0.2)
      (edge_width 0.15)
      (via_size 0.889)
      (via_drill 0.635)
      (via_min_size 0.889)
      (via_min_drill 0.508)
      (uvia_size 0.508)
      (uvia_drill 0.127)
      (uvias_allowed no)
      (uvia_min_size 0.508)
      (uvia_min_drill 0.127)
      (pcb_text_width 0.3)
      (pcb_text_size 1.5 1.5)
      (mod_edge_width 0.15)
      (mod_text_size 1.5 1.5)
      (mod_text_width 0.15)
      (pad_size 0.0005 0.0005)
      (pad_drill 0)
      (allow_soldermask_bridges_in_footprints no)
      (tenting front back)
      (aux_axis_origin 10 15)
      (grid_origin 20 25)
      (visible_elements 7FFFFFFF)
      (pcbplotparams
        (layerselection 0x00000000_00000000_00000000_000000a5)
        (plot_on_all_layers_selection 0x00000000_00000000_00000000_00000000)
        (disableapertmacros no)
        (usegerberextensions yes)
        (usegerberattributes no)
        (usegerberadvancedattributes no)
        (creategerberjobfile no)
        (dashed_line_dash_ratio 12)
        (dashed_line_gap_ratio 3)
        (svgprecision 6)
        (plotframeref no)
        (mode 1)
        (useauxorigin no)
        (hpglpennumber 1)
        (hpglpenspeed 20)
        (hpglpendiameter 15)
        (pdf_front_fp_property_popups yes)
        (pdf_back_fp_property_popups yes)
        (pdf_metadata yes)
        (pdf_single_document no)
        (dxfpolygonmode yes)
        (dxfimperialunits yes)
        (dxfusepcbnewfont yes)
        (psnegative no)
        (psa4output no)
        (plot_black_and_white yes)
        (plotinvisibletext no)
        (sketchpadsonfab no)
        (plotpadnumbers no)
        (hidednponfab no)
        (sketchdnponfab yes)
        (crossoutdnponfab yes)
        (subtractmaskfromsilk no)
        (outputformat 1)
        (mirror no)
        (drillshape 1)
        (scaleselection 1)
        (outputdirectory \"\")
      )
    )"
  `)
})

